repos:

# Some common, basic fixes and precautions (uses pre-commit package)
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace  # trims trailing whitespace
    -   id: check-merge-conflict # checks for files that contain merge conflict strings
    -   id: mixed-line-ending    # replaces mixed line endings
        args: [--fix, lf]

# Black formatting
-   repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
    - id: black
      language_version: python3
      args: [--line-length=125]

# PEP8 compliance (maybe add flake8 later)
#-   repo: https://gitlab.com/pycqa/flake8
#    rev: 6.0.0
#    hooks:
#    - id: flake8
